site_name: IAM client library
nav:
  - Home: index.md
  - "Introduction":
      - "Overview": intro/overview.md
      - "Architecture": intro/architeecture.md
      - "Domain Hierarchy": intro/domainhierarchy.md
  - "Guides":
      - "Authentication": guides/authentication.md
      - "Authorization": guides/authorization.md
      - "Application": guides/application.md
      - "Asset": guides/asset.md
      - "Organization": guides/organization.md
      - "Role": guides/role.md
  - API: api/modules.md
theme: readthedocs

docs_dir: docs
site_dir: site
